version: "2.2"
networks:
    l2pnet:
        driver: bridge
        ipam:
           config:
               - subnet: 172.18.0.0/16
                 gateway: 172.18.0.1
services:
    ethereum-monitor:
        hostname: ethereum-monitor
        container_name: ethereum-monitor
        image: rwthacis/eth-netstats
        command: ["/bin/sh", "-c", "npm start > netstats.log 2>&1"]
        environment:
            - "WS_SECRET=eth-net-stats-secret"
        ports:
            - "3000:3000"
        networks:
            - l2pnet
    ethereum-boot:
        hostname: ethereum-boot
        container_name: ethereum-boot
        depends_on: ["ethereum-monitor"]
        image: rwthacis/monitored-eth-client
        environment:
            - "ETHEREUM_MONITOR=ethereum-monitor:3000"
            - "GETH_VERBOSITY=3"
        ports:
            - "30303"
            - "30303/udp"
            - "8545:8545"
        networks:
            - l2pnet
    las2peer-boot:
        hostname: las2peer.dbis.rwth-aachen.de
        container_name: las2peer-boot
        depends_on: ["ethereum-boot"]
        image: rwthacis/las2peer
        volumes:
            - ./share/agents:/app/las2peer/etc/agents
            - ./share/ssl:/app/las2peer/etc/ssl
            - ./share/lib:/app/las2peer/lib
            - ./share/properties:/app/las2peer/properties
            - ./share/service:/app/las2peer/service
        environment:
            - "LAS2PEER_ETH_HOST=ethereum-boot"
            - "EXTRA_ETH_WAIT=40"
        ports:
            - "9080"
            - "9080/udp"
            - "8001"
            - "8080"
            - "9098:9098"
        networks:
            l2pnet:
                ipv4_address: 172.18.0.10
        stdin_open: true
        tty: true
