    ethereum-peer-1:
        container_name: ethereum-peer-1
        hostname: ethereum-peer-1
        depends_on: ["ethereum-monitor", "ethereum-boot"]
        image: rwthacis/monitored-eth-client
        cpus: "CPULIMIT"
        environment:
            - "PEER_MINE=1"
            - "ETHEREUM_BOOTSTRAP=ethereum-boot:30303"
            - "ETHEREUM_MONITOR=ethereum-monitor:3000"
            - "GETH_VERBOSITY=3"
        ports:
            - "30303"
            - "30303/udp"
            - "8545"
        networks:
            - l2pnet
    las2peer-peer-1:
        container_name: las2peer-peer-1
        hostname: las2peer-peer-1
        depends_on: ["ethereum-peer-1", "las2peer-boot"]
        image: rwthacis/las2peer
        volumes:
            - ./share/agents:/app/las2peer/etc/agents
            - ./share/ssl:/app/las2peer/etc/ssl
            - ./share/lib:/app/las2peer/lib
            - ./share/properties:/app/las2peer/properties
            - ./share/service:/app/las2peer/service
        environment:
            - "LAS2PEER_CONFIG_ENDPOINT=172.18.0.10:8001"
            - "LAS2PEER_BOOTSTRAP=172.18.0.10:9000"
            - "LAS2PEER_ETH_HOST=ethereum-peer-1"
        ports:
            - "9000"
            - "9000/udp"
            - "8080"
        networks:
            - l2pnet
        stdin_open: true
        tty: true
